spring.datasource.url=jdbc:mysql://127.0.0.1:3306/arrowhead?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=orchestrator
spring.datasource.password=KbgD2mTr8DQ4vtc
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
server.address=0.0.0.0
server.port=8441
domain.name=127.0.0.1
domain.port=8441
sr_address=127.0.0.1
sr_port=8443
auth_address=127.0.0.1
auth_port=8445
core_system_name=ORCHESTRATOR
server.ssl.enabled=true
server.ssl.key-store-type=PKCS12
server.ssl.key-store=file:/Users/chinmayakumarnayak/Desktop/smarthome-demo-bidirect/certificates/orchestrator.p12
server.ssl.key-store-password=123456
server.ssl.key-alias=orchestrator.smarthome.demo.arrowhead.eu
server.ssl.key-password=123456
server.ssl.client-auth=need
server.ssl.trust-store-type=PKCS12
server.ssl.trust-store=file:/Users/chinmayakumarnayak/Desktop/smarthome-demo-bidirect/certificates/truststore.p12
server.ssl.trust-store-password=123456
disable.hostname.verifier=true
token.security.filter.enabled=true
