spring.datasource.url=jdbc:mysql://127.0.0.1:3306/arrowhead?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=service_registry
spring.datasource.password=ZzNNpxrbZGVvfJ8
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
server.address=0.0.0.0
server.port=8443
domain.name=127.0.0.1
domain.port=8443
coap.server.enabled=false
core_system_name=SERVICEREGISTRY
ping_scheduled=false
ttl_scheduled=false
use_strict_service_intf_name_verifier=false
use_strict_service_definition_verifier=false
allow_self_addressing=true
allow_non_routable_addressing=true
server.ssl.enabled=true
server.ssl.key-store-type=PKCS12
server.ssl.key-store=file:/Users/chinmayakumarnayak/Desktop/smarthome-demo/certificates/serviceregistry.p12
server.ssl.key-store-password=123456
server.ssl.key-alias=serviceregistry.smarthome.demo.arrowhead.eu
server.ssl.key-password=123456
server.ssl.client-auth=need
server.ssl.trust-store-type=PKCS12
server.ssl.trust-store=file:/Users/chinmayakumarnayak/Desktop/smarthome-demo/certificates/truststore.p12
server.ssl.trust-store-password=123456
disable.hostname.verifier=true
token.security.filter.enabled=true
